### ISSUE TITLE
Done function

### ISSUE THREAD

**Issue by andrewfritz86** [GLosch/rails-cookbook#4]
- define recipe model constructor
- define recipe view constructor with a render fucntion
- within done function, loop through parsed data (forEach), for each object, create a model, then create a view which watches that model. Then try calling render on that view.

**Comment by GLosch** [comment]
You must've knows this ticket would inevitably get reassigned to you. :-)

So far nothing is breaking (hooray!), but the RecipeView.render function isn't getting triggered. The culprit is almost certainly this line: https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/backbone/views/RecipeView.js#L7

...specifically what it's listening to -- Cookbook.Views.FormView seems to exist at this stage (in debugger it returns `function child()`, but I think it's not yet instantiated. If I try to trigger `this.render()` it throws an error that Mustache is not defined.

**Comment by andrewfritz86** [comment]
Any progress here?

**Comment by GLosch** [comment]
Nope, I couldn't figure this one out so I did some styling and other odds and ends.

**Comment by GLosch** [comment]
I'm coming in tomorrow and we can discuss then if you have any ideas for resolving this one.
